import React from "react";

// MUI stuff
import { makeStyles } from "@material-ui/core/styles";
import {
  Typography,
  Grid,
} from "@material-ui/core";

import ArrowRightAltIcon from "@material-ui/icons/ArrowRightAlt";

import ghostrewardStakinglogo from "../../../../assets/ghostReward/ghostrewardStakinglogo.svg";
import ghostrewardVeteranlogo from "../../../../assets/ghostReward/ghostrewardVeteranlogo.svg";
import FontSize from "../../../../utils/FontSize";

const useStyles = makeStyles((theme) => ({
  stakingLogo: {
    marginBottom: 20,
  },
  title: {
    fontSize: FontSize.ml,
    width: 155,
  },
  description: {
    fontSize: FontSize.sm,
    color: theme.palette.secondary.textColor,
    width: 220,
    marginTop: 20,
  },
  btnarrow: {
    display: "flex",
    alignItems: "center",
    marginTop: 35,
  },
  btn: {
    marginRight: 15,
    fontSize: FontSize.size16,
    color: theme.palette.secondary.textColor,
  },
  arrow: {
    cursor: "pointer",
  },
}));

const arr = [
  {
    logo: ghostrewardStakinglogo,
    title: "Staking",
    description:
      "Staking ghost allows you to share in the fees generated by the ghost blockchain. Staking has no minimum coin requirements.",
    btn: "Start staking",
  },
  {
    logo: ghostrewardVeteranlogo,
    title: "Become a Ghost veteran",
    description:
      "Becoming a ghost veteran requires at least 20,000 ghost and is the best way to earn in the fees generated by the ghost blockchain.",
    btn: "Start now",
  },
];
const RewardRightSide = () => {
  const classes = useStyles();
  return (
    <Grid container>
      {arr.map((data) => (
        <Grid item sm={6} xs={12}>
          <img
            src={data.logo}
            alt="Staking logo"
            className={classes.stakingLogo}
          />
          <Typography className={classes.title}>{data.title}</Typography>
          <Typography className={classes.description}>
            {data.description}
          </Typography>
          <div className={classes.btnarrow}>
            <Typography className={classes.btn}>{data.btn}</Typography>
            <ArrowRightAltIcon fontSize="large" className={classes.arrow} />
          </div>
        </Grid>
      ))}
    </Grid>
  );
};

export default RewardRightSide;
